language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd arithmeticoperations  # enter Maven root directory
  - ls -la # this command just prints the contents of the current working directory.


after_success:
- bash <(curl -s https://codecov.io/bash) -t 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 # replace the 1036eb64-2d96-44c6-b132-0dde4e7dfcca with your repository's token obtained by CodeCov
